// Generated by CoffeeScript 1.3.3

jQuery.cssHooks.kittyness = {
  get: function(elem, computed, extra) {
    var data;
    data = jQuery.data(elem, 'css_cats');
    return data && data.length || 0;
  },
  set: function(elem, value) {
    var cats, data, num;
    num = parseInt(value, 10);
    cats = data = jQuery.data(elem, 'css_cats') || [];
    num -= cats.length;
    if (num >= 0) {
      while (num--) {
        cats.push("url(pictures/kitty.svg) " + ((Math.random() * 100).toFixed()) + "% " + ((Math.random() * 100).toFixed()) + "% / 10% no-repeat");
      }
    } else {
      cats.splice(num, -num);
    }
    jQuery.data(elem, 'css_cats', cats);
    jQuery.style(elem, 'background', cats.join());
    return jQuery.style(elem, 'background-color', cats.length && '#fff' || '');
  }
};

jQuery.cssNumber.kittyness = true;

jQuery.easing.bumble = function(percent, current, start, stop, duration) {
  return percent * (10 - percent * 9);
};

jQuery.attrHooks.superprop = {
  get: function(elem) {
    console.log('get superprop', jQuery.data(elem, 'superprop'));
    return jQuery.data(elem, 'superprop');
  },
  set: function(elem, value) {
    console.log('set superprop', value);
    return jQuery.data(elem, 'superprop', value);
  }
};

jQuery.event.special.custom = {
  noBubble: true,
  setup: function(data, ns, eventHanle) {},
  teardown: function(ns, eventHandle) {},
  add: function(handleObj) {},
  remove: function(handleObj) {},
  trigger: function(data) {},
  handle: function(event) {},
  _default: function(data) {},
  preDispatch: function(data) {},
  postDispatch: function(event) {}
};

jQuery.event.special.beforeunload = {
  setup: function(data, namespaces, eventHandle) {
    if (jQuery.isWindow(this)) {
      return this.onbeforeunload = eventHandle;
    }
  },
  teardown: function(namespaces, eventHandle) {
    if (this.onbeforeunload === eventHandle) {
      return this.onbeforeunload = null;
    }
  }
};

jQuery.event.special.empty = {
  setup: function(data, namespaces, eventHandle) {
    var elem,
      _this = this;
    jQuery.data(elem = this, data = {});
    return data.timer = setInterval(function() {
      if (elem.innerHTML.length === 0) {
        data.triggered || $(_this).trigger('empty');
        return data.triggered = true;
      } else if (data.triggered) {
        return data.triggered = false;
      }
    }, 100);
  },
  teardown: function(namespaces, eventHandle) {
    return clearInterval(jQuery.data(this, 'empty_event').timer);
  }
};

jQuery.ajaxPrefilter("data types", function(s, originalSettings, jqXHR) {
  return "transport";
});

jQuery.ajaxTransport("transport", function(s) {
  if (condition) {
    return {
      send: function(headers, callback) {},
      abort: function() {}
    };
  } else {

  }
});

jQuery.ajaxSetup({
  accepts: {
    script: "text/javascript, application/javascript, application/ecmascript, application/x-ecmascript"
  },
  contents: {
    script: /javascript|ecmascript/
  },
  converters: {
    "text script": function(text) {
      jQuery.globalEval(text);
      return text;
    }
  }
});

jQuery.expr[':'].mailto = function(node, index, props, nodes) {
  if (node.href && node.href.match(/^mailto:/)) {
    if (!props[3]) {
      return true;
    } else {
      return node.href.replace(/^.*@/, '') === props[3];
    }
  }
};
